### ISSUE TITLE
A11y checklist Qatar Museums (sprint 2)

### ISSUE THREAD

**Issue by irisvw** [irisvw/all-human-accessible-website#17]
- [x] All inputs in a form are associated with a corresponding label element.
- [ ] Use a for/id pairing to guarantee the highest level of browser/assistive technology support.
- [x] Use fieldset and legend elements where appropriate.
- [ ] Inputs use autocomplete where appropriate.
- [ ] Check your content in specialized browsing modes. Increasing scale to 200% causes script that appends images to stop functioning.
- [ ] Turning on high contrast makes SVG icons invisible (black on black).
- [ ] Turning on high contrast makes the focus style on the filter buttons too subtle.
- [ ] Make sure all animation obeys the prefers-reduced-motion media query.
- [ ] Check the contrast of borders for input elements (text input, radio buttons, checkboxes, etc.).
